## Example Exam Questions Chapter 4

In [1]:
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype

import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

| Functie (`scipy.stats`) | Statistiekdoel | Wanneer gebruiken? | Voorbeeld Input Data |
| :--- | :--- | :--- | :--- |
| `chisquare()` | **Goodness-of-Fit** | Eén variabele: checken of data een theoretische verdeling volgt. | Een lijst met aantallen: `[328, 334, 372, 327]` |
| `chi2.sf()` | **P-waarde berekening** | Als je de $\chi^2$-waarde al hebt en alleen de p-waarde nodig hebt. | Een getal: `chi_squared` (en df) |
| `chi2_contingency()` | **Test van Onafhankelijkheid** | Twee variabelen: checken of er een relatie is tussen twee categorieën. | Een 2D-matrix (tabel): `[[10, 20], [15, 25]]` |

## Exercise 1
Criminologists have long debated whether there is a relationship between weather conditions and the number of crimes committed. In 1988, an article “Is there a
Season for Homicide?” (Criminology, 1988: 287-296) classified 1361 homicides by season, resulting
in the data below.  
Is there an association between season and the number of murders committed?

H0 => er is geen verband tussen de seizoenen en het aantal moorden

H1 => er is een verband, het aantal moorden hangt af van het seizoen

In [2]:
dfmurders = pd.DataFrame(data={
    'season': ['winter', 'spring','summer','autumn'],
    'number_of_murders': [328, 334, 372, 327]
})

In [3]:
observed = dfmurders['number_of_murders']
chi2, p = stats.chisquare(observed)

print(p)

0.25775920748891

## Exercise 2
A random sample of individuals was taken, and each individual was classified according to their level of education and their sense of spirituality.
Is there an association between the level of education and the sense of spirituality?

Null Hypothesis ($H_0$): There is no association between education level/group and sense of spirituality (they are independent).

Alternative Hypothesis ($H_1$): There is an association between education level/group and sense of spirituality (they are dependent).

In [4]:
dfspirituality = pd.DataFrame(data={
    'sense_of_spirituality': ['lot', 'moderate','little','none'],
    'alfa_scientist': [56, 162, 198, 211],
    'beta_scientist': [56, 223, 243, 239],
    'not_scientist': [109, 164, 74, 28]
})
dfspirituality.head()

  sense_of_spirituality  alfa_scientist  beta_scientist  not_scientist
0                   lot              56              56            109
1              moderate             162             223            164
2                little             198             243             74
3                  none             211             239             28

In [5]:
observed = dfspirituality[['alfa_scientist', 'beta_scientist', 'not_scientist']]
chi2, p, df, expected = stats.chi2_contingency(observed)
print(p)

2.9123307545358886e-43

## Exercise 4

In an experiment, 150 patients were divided into three groups of 45, 45 and 60 patients each. Two groups were given a new drug in different doses and the third group was given a placebo. The way the patients felt after using the drug are shown in the data frame below. Is there evidence at the 5% significance level that there is a difference in the condition between the three groups of patients?

In [6]:
dfexperiment = pd.DataFrame(data={
    'state': ['better', 'equal', 'worse'],
    'placebo': [16, 20, 9],
    'half_dosis': [17, 18, 10],
    'full_dosis': [26, 20, 14]
}).set_index('state')
dfexperiment.head()

        placebo  half_dosis  full_dosis
state
better       16          17          26
equal        20          18          20
worse         9          10          14

In [7]:
observed = dfexperiment[['placebo', 'half_dosis', 'full_dosis']]
chi2, p, df, expected = stats.chi2_contingency(observed)
print(f"Chi-square Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {df}")

Chi-square Statistic: 1.41691609254438
P-value: 0.8412496535217702
Degrees of Freedom: 4